web:
  build: .
  volumes:
    - .:/web-app
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: postgres:latest
  ports:
    - "5432:5432"
  env_file:
    - '.env.db'


#     bundle install  docker-compose run web bundle install
# rails s docker-compose run web rails s
# rspec spec/path/to/spec.rb  docker-compose run web rspec spec/path/to/spec.rb
# RAILS_ENV=test rake db:create docker-compose run -e RAILS_ENV=test web rake db:create
# tail -f log/development.log docker-compose run web tail -f log/development.log