# Docker-compose is useful for the development of your application. This automatically spins up
# a container based off the Dockerfile in the working dir and links it to a postgres instance.
# Modify as necessary to suit your needs
  # image: jaicob/web-app
# Followed tips in this tutorial to add Redis and Sidekiq: http://allenan.com/docker-rails-dev-environment-for-osx/

db:
  image: postgres:latest
  ports:
    - "5432:5432"

redis:
  image: redis
  ports: 
    - "6379:6379"

web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  volumes:
    - .:/home/rails/my-app
  ports:
    - "3000:3000"
  links:
    - db
    - redis
    - sidekiq
  environment:
    - RACK_ENV=development
    - RAILS_ENV=development

sidekiq:
  build: .
  command: bundle exec sidekiq -e development -c 25
  environment:
    SECRET_KEY_BASE: abcdefg
    RAILS_ENV: development
  links:
    - db
    - redis
