source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'devise_invitable'
gem 'foundation-rails'
gem 'pg'
gem 'figaro'
gem 'annotate'
gem 'friendly_id', '~> 5.1.0'
gem 'carrierwave'
gem 'rmagick'
gem 'foundation-icons-sass-rails'
gem 'best_in_place', '~> 3.0.1'
gem 'grape'
gem 'hashie-forbidden_attributes'
group :development do
  gem 'better_errors'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'rubocop'
end
group :test do
  gem 'database_cleaner'
  gem 'launchy'
  gem 'ci_reporter'
  gem 'ci_reporter_rspec'
end
group :production do
  gem 'unicorn'
  gem 'unicorn-rails'
end