branch-defaults:
  default:
    environment: axon-web-dev
  develop:
    environment: axon-web-dev
  development:
    environment: axon-web-dev
global:
  application_name: axon-web
  default_ec2_keyname: dev-env
  default_platform: Docker 1.6.0
  default_region: us-east-1
  profile: null
  sc: git
