branch-defaults:
  master:
    environment: staging
  setup-staging:
    environment: axon-staging
deploy:
  artifact: .elasticbeanstalk/Docker/Dockerrun.aws.json
global:
  application_name: axon-web
  default_ec2_keyname: staging-env
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running Multi-container Docker
    1.7.1 (Generic)
  default_region: us-east-1
  profile: eb-cli
  sc: git
