development:
  adapter: postgresql
  encoding: unicode
  database: web_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: web_test
  pool: 5
  username: postgres
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: web_production
  pool: 5
  username: jaicob
  password: