development: &default
  adapter:  postgresql
  encoding: unicode
  template: template0
  pool:     5
  database: web_development
  username: postgres
  password: 
  host:     db

test: &test
  adapter:  postgresql
  host:     db
  encoding: unicode
  database: web_test
  pool:     5
  username: postgres
  password: 
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  template: template0
  pool:     5
  host: <%= ENV['RDS_HOSTNAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: <%= ENV['RDS_PORT'] %>
  database: <%= ENV['RDS_DB_NAME'] %>

staging:
  adapter: postgresql
  encoding: unicode
  template: template0
  pool:     5
  host: <%= ENV['RDS_HOSTNAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: <%= ENV['RDS_PORT'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
